# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-05 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilingual_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='multilingual_survey.SurveyAnswer', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='other_answer',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Other answer'),
        ),
    ]
