# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-15 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilingual_survey', '0003_surveyresponse_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='meta_integer',
            field=models.IntegerField(blank=True, null=True, verbose_name='meta integer'),
        ),
    ]
