# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilingual_survey', '0004_surveyanswer_meta_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswertranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='SubTitle'),
        ),
    ]
